version: "3.1"

services:
  # Admin Services
  php_admin:
        build: ./admin
        container_name: php_admin
        ports:
            - "8081:80"
        restart: on-failure
        networks:
            - default
            
  # Student Services
  php_student:
        build: ./student
        container_name: php_student
        ports:
            - "8082:80"
        restart: on-failure
        networks:
            - default

  # Assignment Services
  php_assignment:
        build: ./assignment-service
        container_name: php_assignment
        ports:
            - "8084:80"
        restart: on-failure
        networks:
            - default
  
 
  # Solution Services
  php_solution:
        build: ./solution-service
        container_name: php_solution
        ports:
            - "8085:80"
        restart: on-failure
        networks:
            - default
 
  
  # Result Services
  php_result:
        build: ./result-service
        container_name: php_result
        ports:
            - "8086:80"
        restart: on-failure
        networks:
            - default


  # User Services
  php_user:
        build: ./user-service
        container_name: php_user
        ports:
            - "8083:80"
        restart: on-failure
        networks:
            - default
  mysql_microservices:
      image: mysql:8.0
      container_name: mysql_microservices
      volumes:
          - ./microservices.sql:/docker-entrypoint-initdb.d/microservices.sql
      ports:
          - "3307:3306"
      command: --default-authentication-plugin=mysql_native_password
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: microservices
          MYSQL_USER: user
          MYSQL_PASSWORD: password
      
      networks:
          - default
  phpmyadmin_microservices:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin_microservices
      links:
          - mysql_microservices:db
      ports:
          - 9081:80
      environment:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          PMA_HOST: mysql_microservices
          PMA_PORT: 3306

  
volumes:
    mysql_microservices:
